image: node:18.16.0

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH

pages:
  script:
    - ci/pages-preparation.sh
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
